-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PixUp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PixUp` ;

-- -----------------------------------------------------
-- Schema PixUp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PixUp` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `PixUp` ;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_ESTADO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_ESTADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_MUNICIPIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_MUNICIPIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` VARCHAR(45) NOT NULL,
  `TBL_ESTADO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_MUNICIPIO_TBL_ESTADO`
    FOREIGN KEY (`TBL_ESTADO_ID`)
    REFERENCES `PixUp`.`TBL_ESTADO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_MUNICIPIO_TBL_ESTADO_idx` ON `PixUp`.`TBL_MUNICIPIO` (`TBL_ESTADO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_COLONIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_COLONIA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_COLONIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `CP` CHAR(5) NULL,
  `TBL_MUNICIPIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_COLONIA_TBL_MUNICIPIO1`
    FOREIGN KEY (`TBL_MUNICIPIO_ID`)
    REFERENCES `PixUp`.`TBL_MUNICIPIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_COLONIA_TBL_MUNICIPIO1_idx` ON `PixUp`.`TBL_COLONIA` (`TBL_MUNICIPIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_TIPO_DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_TIPO_DOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_TIPO_DOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_USUARIO` (
  `ID` INT NOT NULL,
  `NOMBRE` VARCHAR(40) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(40) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(40) NOT NULL,
  `PASSWORD` CHAR(150) NOT NULL,
  `EMAIL` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_DOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_DOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CALLE` VARCHAR(60) NOT NULL,
  `NUM_EXTERIOR` VARCHAR(30) NOT NULL,
  `NUM_INTERIOR` VARCHAR(30) NOT NULL,
  `TBL_COLONIA_ID` INT NOT NULL,
  `TBL_TIPO_DOMICILIO_ID` INT NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_COLONIA1`
    FOREIGN KEY (`TBL_COLONIA_ID`)
    REFERENCES `PixUp`.`TBL_COLONIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_TIPO_DOMICILIO1`
    FOREIGN KEY (`TBL_TIPO_DOMICILIO_ID`)
    REFERENCES `PixUp`.`TBL_TIPO_DOMICILIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `PixUp`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_COLONIA1_idx` ON `PixUp`.`TBL_DOMICILIO` (`TBL_COLONIA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_TIPO_DOMICILIO1_idx` ON `PixUp`.`TBL_DOMICILIO` (`TBL_TIPO_DOMICILIO_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_USUARIO1_idx` ON `PixUp`.`TBL_DOMICILIO` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_TIPO_NOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_TIPO_NOTIFICACION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_TIPO_NOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(40) NOT NULL,
  `RUTA_PLANTILLA` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_NOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_NOTIFICACION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_NOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA_NOTIFICACION` DATETIME NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  `TBL_TIPO_NOTIFICACION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_NOTIFICACION_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `PixUp`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_NOTIFICACION_TBL_TIPO_NOTIFICACION1`
    FOREIGN KEY (`TBL_TIPO_NOTIFICACION_ID`)
    REFERENCES `PixUp`.`TBL_TIPO_NOTIFICACION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_NOTIFICACION_TBL_USUARIO1_idx` ON `PixUp`.`TBL_NOTIFICACION` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_NOTIFICACION_TBL_TIPO_NOTIFICACION1_idx` ON `PixUp`.`TBL_NOTIFICACION` (`TBL_TIPO_NOTIFICACION_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_ORDEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_ORDEN` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_ORDEN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COSTO_TOTAL` FLOAT NOT NULL,
  `FECHA` TIMESTAMP NOT NULL,
  `CANTIDAD_TOTAL` INT NOT NULL,
  `ESTATUS_ENVIO` TINYINT(1) NOT NULL,
  `COSTO_ENVIO` FLOAT NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_ORDEN_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `PixUp`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_ORDEN_TBL_USUARIO1_idx` ON `PixUp`.`TBL_ORDEN` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_PAGO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_PAGO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO_TARJETA` CHAR(4) NOT NULL,
  `FECHA` TIMESTAMP NOT NULL,
  `TBL_ORDEN_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_PAGO_TBL_ORDEN1`
    FOREIGN KEY (`TBL_ORDEN_ID`)
    REFERENCES `PixUp`.`TBL_ORDEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_PAGO_TBL_ORDEN1_idx` ON `PixUp`.`TBL_PAGO` (`TBL_ORDEN_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_ARTISTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_ARTISTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_ARTISTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_DISQUERA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_DISQUERA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_DISQUERA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_GENERO_MUSICAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_GENERO_MUSICAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_GENERO_MUSICAL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_DISCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_DISCO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_DISCO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(200) NOT NULL,
  `PRECIO` FLOAT NOT NULL,
  `EXISTENCIA` INT NOT NULL,
  `DESCUENTO` FLOAT NOT NULL,
  `FECHA_LANZAMIENTO` DATE NOT NULL,
  `IMAGEN` VARCHAR(120) NOT NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  `TBL_DISQUERA_ID` INT NOT NULL,
  `TBL_GENERO_MUSICAL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DISCO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `PixUp`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_DISQUERA1`
    FOREIGN KEY (`TBL_DISQUERA_ID`)
    REFERENCES `PixUp`.`TBL_DISQUERA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_GENERO_MUSICAL1`
    FOREIGN KEY (`TBL_GENERO_MUSICAL_ID`)
    REFERENCES `PixUp`.`TBL_GENERO_MUSICAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_ARTISTA1_idx` ON `PixUp`.`TBL_DISCO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_DISQUERA1_idx` ON `PixUp`.`TBL_DISCO` (`TBL_DISQUERA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_GENERO_MUSICAL1_idx` ON `PixUp`.`TBL_DISCO` (`TBL_GENERO_MUSICAL_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_DETALLE_ORDEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_DETALLE_ORDEN` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_DETALLE_ORDEN` (
  `ID_DISCO` INT NULL,
  `ID_ORDEN` INT NULL,
  `CANTIDAD` INT NOT NULL,
  `COSTO` FLOAT NOT NULL,
  `TBL_ORDEN_ID` INT NOT NULL,
  `TBL_DISCO_ID` INT NOT NULL,
  PRIMARY KEY (`TBL_ORDEN_ID`, `TBL_DISCO_ID`),
  CONSTRAINT `fk_TBL_DETALLE_ORDEN_TBL_ORDEN1`
    FOREIGN KEY (`TBL_ORDEN_ID`)
    REFERENCES `PixUp`.`TBL_ORDEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DETALLE_ORDEN_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `PixUp`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DETALLE_ORDEN_TBL_DISCO1_idx` ON `PixUp`.`TBL_DETALLE_ORDEN` (`TBL_DISCO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PixUp`.`TBL_CANCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PixUp`.`TBL_CANCION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PixUp`.`TBL_CANCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(100) NOT NULL,
  `DURACION` TIME NOT NULL,
  `TBL_DISCO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_CANCION_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `PixUp`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_CANCION_TBL_DISCO1_idx` ON `PixUp`.`TBL_CANCION` (`TBL_DISCO_ID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
